appVersion: 1.0.0
description: 'Open Distro for Elasticsearch'
engine: gotpl
kubeVersion: ^1.10.0-0
maintainers:
- email: derek.heldt-werle@viasat.com
  name: Derek Heldt-Werle
- email: kalvin.chau@viasat.com
  name: Kalvin Chau
name: opendistro-es
sources:
- https://pages.git.viasat.com/ATG/charts
version: 1.1.0
