# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
{{- if and .Values.kibana.enabled .Values.kibana.config }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "opendistro-es.fullname" . }}-kibana-config
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "opendistro-es.labels.standard" . | indent 4 }}
data:
  kibana.yml: {{ toYaml .Values.kibana.config | b64enc }}
{{- end }}
