# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "opendistro-es.fullname" . }}-es-config
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "opendistro-es.labels.standard" . | indent 4 }}
type: Opaque
data:
  {{- if .Values.elasticsearch.config }}
  elasticsearch.yml: {{ toYaml .Values.elasticsearch.config | b64enc | quote }}
  {{- end }}
  {{- if .Values.elasticsearch.log4jConfig }}
  log4j2.properties: {{ .Values.elasticsearch.log4jConfig | b64enc | quote }}
  {{- end }}
  logging.yml: {{ toYaml .Values.elasticsearch.loggingConfig | b64enc | quote }}
