# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-config
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "opendistro-es.labels.standard" . | indent 4 }}
type: Opaque
data:
  elasticsearch.yml: {{ toYaml .Values.elasticsearch.config | b64enc | quote }}
  logging.yml: {{ toYaml .Values.elasticsearch.loggingConfig | b64enc | quote }}
  log4j2.properties: {{ toYaml .Values.elasticsearch.log4jConfig | b64enc | quote }}
